### ISSUE TITLE
Should we contribute code here or to the prestodb client?

### ISSUE THREAD

**Issue by matthewwardrop** [prestosql/presto-python-client#1]
I have an outstanding PR over a the prestodb/presto-python-client repo (https://github.com/prestodb/presto-python-client/pull/90), which does not seem to be getting much attention. Is this the new place to commit? [The pypi package does not seem to point to this one, despite the README.md file suggesting that is how it should be installed].

**Comment by electrum** [comment]
Please contribute it here! We’re still setting up development here and will update the pypi package name for this version and do a release soon.

**Comment by findepi** [comment]
The current pypi project page is https://pypi.org/project/presto-client/ .
@matthewwardrop looking forward to your first contribution here!

**Comment by matthewwardrop** [comment]
Hurrah! Thank you! I'll resubmit my patch here :).
