### ISSUE TITLE
Add explicit support for extra credentials

### ISSUE THREAD

**Issue by findepi** [prestosql/presto-python-client#14]
The extra credentials are supported today by setting HTTP headers directly.

However, the header encoding is non-trivial, so they should be supported as a first-class configuration.

Related https://github.com/prestosql/presto-python-client/issues/13, https://github.com/dropbox/PyHive/issues/311

**Comment by findepi** [comment]
Duplicates https://github.com/prestosql/presto-python-client/issues/6

**Comment by zyxue** [comment]
Dou you have an example of setting the http header with extra credentials, please?

**Comment by findepi** [comment]
@zyxue i provided an example under #6.
Also, i invite you to [Presto community slack](https://prestosql.io/slack.html). We have dedicated `python-client` channel there.
See you there!
