### ISSUE TITLE
Get AttributeError: 'Response' object has no attribute 'is_redirect' Error when running on Python 2.7

### ISSUE THREAD

**Issue by RugratsJ** [prestosql/presto-python-client#17]
Got the following error when running on Amazon EMR management node.

```
Traceback (most recent call last):
  File "./t1.py", line 10, in <module>
    cur.execute('SELECT * FROM rdsoracle.tpch100g.orders limit 10')
  File "/usr/lib/python2.7/dist-packages/presto/dbapi.py", line 236, in execute
    result = self._query.execute()
  File "/usr/lib/python2.7/dist-packages/presto/client.py", line 509, in execute
    response = self._request.post(self._sql)
  File "/usr/lib/python2.7/dist-packages/presto/client.py", line 341, in post
    while http_response is not None and http_response.is_redirect:
AttributeError: 'Response' object has no attribute 'is_redirect'
```

Below is the Python code:

```python
import presto
conn = presto.dbapi.connect(
    host='localhost',
    port=8081,
    user='hadoop',
    catalog='rdsoracle',
    schema='tpch100g',
)
cur = conn.cursor()
cur.execute('SELECT * FROM rdsoracle.tpch100g.orders limit 10')
rows = cur.fetchall()
```

**Comment by RugratsJ** [comment]
Never mind. It seems to me, I have to use python3 instead of python2.

**Comment by findepi** [comment]
@RugratsJ thanks for reporting.

until we complete https://github.com/prestosql/presto-python-client/issues/4 we should support Python 2.7
and after https://github.com/prestosql/presto-python-client/issues/4 we should fail cleanly on Python < 3.

**Comment by dhruvp-8** [comment]
@findepi I would like to work on this issue.

**Comment by dhruvp-8** [comment]
Adding the condition `hasattr(http_response, 'is_redirect')` should solve this issue. However what should be the outcome AttributeError Exception is raised in [this](https://github.com/prestosql/presto-python-client/blob/master/presto/client.py#L341) code

**Comment by findepi** [comment]
Ideally we would just delegate to the library to handle the redirects. And we do, unless a `redirect_handler` is installed.
Sadly, there is a default implementation of a redirect handler:
https://github.com/prestosql/presto-python-client/blob/2a09d4c1792dce9a591d97aeb73067aa064b1f2e/presto/client.py#L208

AFAICT, In the Java client we don't have such logic, I don't know why it is needed here.
I think we should simply remove the default.

@RugratsJ as a temporary workaround please add `redirect_handler=None` to the `presto.dbapi.connect(..)` invocation.

**Comment by findepi** [comment]
FYI this is fixed in master.
However, the underlying problem is likely library inconsistency at runtime.
We run integration tests with Python 2.7 and the line mentioned in traceback
```
  File "/usr/lib/python2.7/dist-packages/presto/client.py", line 341, in post
    while http_response is not None and http_response.is_redirect:
```

_is_ being exercised correctly. 

So @RugratsJ 
- thanks for reporting, this allowed us to do the right thing and remove some incorrect default behavior
- you are running with a different http library version than we test against, so there might be other hiccups
