### ISSUE TITLE
Remove redirect_handler

### ISSUE THREAD

**Issue by findepi** [prestosql/presto-python-client#26]
https://github.com/prestosql/presto-python-client/pull/23#issuecomment-620918048 @electrum 

> I think the purpose of `GatewayRedirectHandler` is to canonicalize the hostname in the URL, likely for a reason related to Kerberos or TLS certificates. However, this seems like the wrong place to handle it. I suggest removing the redirect handler support entirely.

https://github.com/prestosql/presto-python-client/pull/23#issuecomment-621007601 @findepi 

> @electrum i agree, my assessment of the redirect handler is the same. 
Let's do small steps, just in case someone relied on this.
I will merge as is, and create follow up issue to remove the redirect handler altogether.

**Comment by iadi7ya** [comment]
Hi @findepi Can I take this up!

**Comment by findepi** [comment]
@iadi7ya sure, go for it!

**Comment by iadi7ya** [comment]
Hi @findepi I should delete this file: https://github.com/prestosql/presto-python-client/blob/master/presto/redirect.py ?

**Comment by findepi** [comment]
yes, i think so
