### ISSUE TITLE
Allow to specify client certificate path explicitly

### ISSUE THREAD

**Issue by dongwoo1005** [prestosql/presto-python-client#29]
As per discussion in Slack: https://prestosql.slack.com/archives/CFPVDCDHV/p1589924393017200

Currently presto.dbapi.connect api does not have a parameter to explicitly specify client certificate path to connect with SSL/TLS. Client cert should be explicitly configurable.

**Comment by findepi** [comment]
A current workaround, from referenced slack thread:

> After creating the connection object I do
> ```
> conn._http_session.verify = '/path/to/cert' 
> ```
> before creating a cursor.
>
