### ISSUE TITLE
Cursor should implement __iter__

### ISSUE THREAD

**Issue by hashhar** [prestosql/presto-python-client#33]
The Cursor class in `dbapi.py` doesn't implement `__iter__` today meaning that code like `csv_writer.writerows(cursor)` or anything that tries to loop over the Cursor will not work.

**Comment by findepi** [comment]
Maybe we could have API compatibility tests against say psycopg2.

**Comment by hashhar** [comment]
That is a good idea but I'm not sure how that would look in practice. I'll check how other DBApi compliant libraries ensure they adhere to the "spec".

This will also help me check if there are any other existing gaps which need to filled for being "spec compliant".

**Comment by hashhar** [comment]
Turns out there was a project which aimed to make testing for DBApi compliance easy (https://github.com/baztian/dbapi-compliance) but I couldn't find any projects using it (and it's inaccurate in some places and missing coverage in other places) and almost everyone relies on user reports to figure out incompatibility with DBApi 2.0.

I wish there was something like TCK for Python too.
