### ISSUE TITLE
How do I use SSO to get my LDAP credentials to sign into Presto

### ISSUE THREAD

**Issue by bthodla** [prestosql/presto-python-client#40]
I have setup a kerberized Presto Cluster and enabled LDAP integration for end user authentication. This works well from query and BI tools. I am trying to access it from Jupyter Notebooks and would like to know how to setup Single Sign-On (SSO) to get my credentials from LDAP so that I don't have to include the password in my connection string.

**Comment by findepi** [comment]
Let's move this to `#troubleshooting` channel on [our slack](https://prestosql.io/slack.html)
thanks!
